import type { AppKeyword } from "@/lib/types"

/**
 * Demo keywords for RedRain Slots Casino - UK Market (en-GB)
 * Based on ASO research with Egyptian Fortune theme
 * Focus on: slots, casino, egyptian slots, pharaoh, cleopatra, jackpot
 */
export const demoKeywords: Omit<AppKeyword, "id" | "app_data_id" | "created_at" | "updated_at">[] = [
  // Branded Keywords
  {
    keyword: "redrain slots casino",
    search_volume: 12000,
    difficulty: 50.0,
    relevance_score: 95.0,
    category: "branded",
    priority: "high",
    platform: "both",
    recommended_field: "title",
    sort_order: 0,
    brand: true,
    chance: 0.70,
    kei: 150.0,
    results: 200000,
    maximum_reach: 500000,
    conversion_rate: 0.10,
  },
  {
    keyword: "redrain",
    search_volume: 8500,
    difficulty: 30.0,
    relevance_score: 98.0,
    category: "branded",
    priority: "high",
    platform: "both",
    recommended_field: "title",
    sort_order: 1,
    brand: true,
    chance: 0.95,
    kei: 280.0,
    results: 1200,
    maximum_reach: 8500,
    conversion_rate: 0.12,
  },
  {
    keyword: "redrain casino",
    search_volume: 6500,
    difficulty: 35.0,
    relevance_score: 97.0,
    category: "branded",
    priority: "high",
    platform: "both",
    recommended_field: "title",
    sort_order: 2,
    brand: true,
    chance: 0.85,
    kei: 185.7,
    results: 800,
    maximum_reach: 6500,
    conversion_rate: 0.11,
  },

  // Generic High Volume Keywords
  {
    keyword: "casino slots",
    search_volume: 50000,
    difficulty: 30.0,
    relevance_score: 96.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "subtitle",
    sort_order: 3,
    brand: false,
    chance: 0.60,
    kei: 1666.0,
    results: 1500000,
    maximum_reach: 1000000,
    conversion_rate: 0.08,
  },
  {
    keyword: "slots casino",
    search_volume: 45000,
    difficulty: 25.0,
    relevance_score: 94.0,
    category: "generic",
    priority: "high",
    platform: "android",
    recommended_field: "title",
    sort_order: 4,
    brand: false,
    chance: 0.65,
    kei: 1800.0,
    results: 1200000,
    maximum_reach: 800000,
    conversion_rate: 0.09,
  },
  {
    keyword: "free slots",
    search_volume: 47000,
    difficulty: 15.0,
    relevance_score: 97.0,
    category: "generic",
    priority: "high",
    platform: "android",
    recommended_field: "subtitle",
    sort_order: 5,
    brand: false,
    chance: 0.55,
    kei: 3133.0,
    results: 1100000,
    maximum_reach: 600000,
    conversion_rate: 0.07,
  },
  {
    keyword: "jackpot",
    search_volume: 245000,
    difficulty: 75.0,
    relevance_score: 89.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 6,
    brand: false,
    chance: 0.45,
    kei: 3266.0,
    results: 3000000,
    maximum_reach: 2000000,
    conversion_rate: 0.06,
  },
  {
    keyword: "slots",
    search_volume: 320000,
    difficulty: 78.0,
    relevance_score: 95.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 7,
    brand: false,
    chance: 0.45,
    kei: 4100.0,
    results: 45000,
    maximum_reach: 320000,
    conversion_rate: 0.08,
  },
  {
    keyword: "casino games",
    search_volume: 280000,
    difficulty: 75.0,
    relevance_score: 92.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 8,
    brand: false,
    chance: 0.42,
    kei: 3733.0,
    results: 38000,
    maximum_reach: 280000,
    conversion_rate: 0.07,
  },

  // Competitor Keywords
  {
    keyword: "royal spin",
    search_volume: 12000,
    difficulty: 45.0,
    relevance_score: 95.0,
    category: "competitor",
    priority: "high",
    platform: "both",
    recommended_field: "title",
    sort_order: 9,
    brand: false,
    chance: 0.50,
    kei: 266.0,
    results: 500000,
    maximum_reach: 300000,
    conversion_rate: 0.06,
  },
  {
    keyword: "royal spin palace",
    search_volume: 8500,
    difficulty: 35.0,
    relevance_score: 98.0,
    category: "competitor",
    priority: "medium",
    platform: "both",
    recommended_field: "title",
    sort_order: 10,
    brand: false,
    chance: 0.40,
    kei: 242.0,
    results: 300000,
    maximum_reach: 200000,
    conversion_rate: 0.05,
  },
  {
    keyword: "vegas",
    search_volume: 180000,
    difficulty: 70.0,
    relevance_score: 82.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 11,
    brand: false,
    chance: 0.30,
    kei: 2571.0,
    results: 2500000,
    maximum_reach: 1500000,
    conversion_rate: 0.04,
  },

  // Egyptian Theme Keywords
  {
    keyword: "cleopatra slots",
    search_volume: 12000,
    difficulty: 20.0,
    relevance_score: 90.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 12,
    brand: false,
    chance: 0.50,
    kei: 600.0,
    results: 800000,
    maximum_reach: 500000,
    conversion_rate: 0.06,
  },
  {
    keyword: "egyptian slots",
    search_volume: 38000,
    difficulty: 50.0,
    relevance_score: 93.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 13,
    brand: false,
    chance: 0.66,
    kei: 760.0,
    results: 3200,
    maximum_reach: 38000,
    conversion_rate: 0.10,
  },
  {
    keyword: "pharaoh slots",
    search_volume: 62000,
    difficulty: 52.0,
    relevance_score: 94.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 14,
    brand: false,
    chance: 0.68,
    kei: 1192.0,
    results: 5400,
    maximum_reach: 62000,
    conversion_rate: 0.12,
  },
  {
    keyword: "egypt slots",
    search_volume: 88000,
    difficulty: 58.0,
    relevance_score: 96.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 15,
    brand: false,
    chance: 0.65,
    kei: 1517.0,
    results: 8200,
    maximum_reach: 88000,
    conversion_rate: 0.11,
  },
  {
    keyword: "ancient treasure slots",
    search_volume: 25000,
    difficulty: 40.0,
    relevance_score: 88.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 16,
    brand: false,
    chance: 0.58,
    kei: 625.0,
    results: 3500,
    maximum_reach: 25000,
    conversion_rate: 0.08,
  },
  {
    keyword: "pyramid slots",
    search_volume: 18000,
    difficulty: 35.0,
    relevance_score: 87.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 17,
    brand: false,
    chance: 0.62,
    kei: 514.0,
    results: 2800,
    maximum_reach: 18000,
    conversion_rate: 0.07,
  },
  {
    keyword: "cleopatra casino",
    search_volume: 15000,
    difficulty: 38.0,
    relevance_score: 85.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 18,
    brand: false,
    chance: 0.60,
    kei: 395.0,
    results: 3200,
    maximum_reach: 15000,
    conversion_rate: 0.06,
  },
]
