import type { AppKeyword } from "@/lib/types"

/**
 * Demo keywords for RedRain Slots Casino - Social Casino app
 * Based on ASO research with Egyptian Fortune theme
 * Focus on: slots, casino, egypt slots, pharaoh, cleopatra, fortune
 */
export const demoKeywords: Omit<AppKeyword, "id" | "app_data_id" | "created_at" | "updated_at">[] = [
  // Branded Keywords
  {
    keyword: "redrain",
    search_volume: 8500,
    difficulty: 30.0,
    relevance_score: 98.0,
    category: "branded",
    priority: "high",
    platform: "both",
    recommended_field: "title",
    sort_order: 0,
    brand: true,
    chance: 0.95,
    kei: 280.0,
    results: 1200,
    maximum_reach: 8500,
    conversion_rate: 0.12,
  },
  {
    keyword: "redrain fortune",
    search_volume: 5200,
    difficulty: 25.0,
    relevance_score: 99.0,
    category: "branded",
    priority: "high",
    platform: "both",
    recommended_field: "title",
    sort_order: 1,
    brand: true,
    chance: 0.92,
    kei: 193.0,
    results: 850,
    maximum_reach: 5200,
    conversion_rate: 0.15,
  },
  {
    keyword: "redrain slots",
    search_volume: 3200,
    difficulty: 22.0,
    relevance_score: 97.0,
    category: "branded",
    priority: "high",
    platform: "both",
    recommended_field: "title",
    sort_order: 2,
    brand: true,
    chance: 0.90,
    kei: 139.0,
    results: 620,
    maximum_reach: 3200,
    conversion_rate: 0.14,
  },

  // Generic High Volume Keywords (Slots & Casino)
  {
    keyword: "slots",
    search_volume: 320000,
    difficulty: 78.0,
    relevance_score: 95.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 3,
    brand: false,
    chance: 0.45,
    kei: 4100.0,
    results: 45000,
    maximum_reach: 320000,
    conversion_rate: 0.08,
  },
  {
    keyword: "casino games",
    search_volume: 280000,
    difficulty: 75.0,
    relevance_score: 92.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 4,
    brand: false,
    chance: 0.42,
    kei: 3733.0,
    results: 38000,
    maximum_reach: 280000,
    conversion_rate: 0.07,
  },
  {
    keyword: "free slots",
    search_volume: 245000,
    difficulty: 72.0,
    relevance_score: 94.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "subtitle",
    sort_order: 5,
    brand: false,
    chance: 0.48,
    kei: 3403.0,
    results: 32000,
    maximum_reach: 245000,
    conversion_rate: 0.09,
  },
  {
    keyword: "slot machine",
    search_volume: 195000,
    difficulty: 68.0,
    relevance_score: 91.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 6,
    brand: false,
    chance: 0.50,
    kei: 2868.0,
    results: 28000,
    maximum_reach: 195000,
    conversion_rate: 0.08,
  },
  {
    keyword: "jackpot slots",
    search_volume: 165000,
    difficulty: 70.0,
    relevance_score: 93.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 7,
    brand: false,
    chance: 0.46,
    kei: 2357.0,
    results: 25000,
    maximum_reach: 165000,
    conversion_rate: 0.09,
  },
  {
    keyword: "casino",
    search_volume: 450000,
    difficulty: 85.0,
    relevance_score: 88.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 8,
    brand: false,
    chance: 0.35,
    kei: 5294.0,
    results: 65000,
    maximum_reach: 450000,
    conversion_rate: 0.06,
  },

  // Egyptian Fortune Theme Keywords (High Priority)
  {
    keyword: "egypt slots",
    search_volume: 88000,
    difficulty: 58.0,
    relevance_score: 96.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 9,
    brand: false,
    chance: 0.65,
    kei: 1517.0,
    results: 8200,
    maximum_reach: 88000,
    conversion_rate: 0.11,
  },
  {
    keyword: "pharaoh slots",
    search_volume: 62000,
    difficulty: 52.0,
    relevance_score: 94.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 10,
    brand: false,
    chance: 0.68,
    kei: 1192.0,
    results: 5400,
    maximum_reach: 62000,
    conversion_rate: 0.12,
  },
  {
    keyword: "cleopatra slots",
    search_volume: 58000,
    difficulty: 55.0,
    relevance_score: 92.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 11,
    brand: false,
    chance: 0.62,
    kei: 1055.0,
    results: 5200,
    maximum_reach: 58000,
    conversion_rate: 0.11,
  },
  {
    keyword: "fortune slots",
    search_volume: 45000,
    difficulty: 48.0,
    relevance_score: 95.0,
    category: "generic",
    priority: "high",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 12,
    brand: false,
    chance: 0.70,
    kei: 938.0,
    results: 3800,
    maximum_reach: 45000,
    conversion_rate: 0.13,
  },
  {
    keyword: "egyptian slots",
    search_volume: 38000,
    difficulty: 50.0,
    relevance_score: 93.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 13,
    brand: false,
    chance: 0.66,
    kei: 760.0,
    results: 3200,
    maximum_reach: 38000,
    conversion_rate: 0.10,
  },
  {
    keyword: "pharaoh",
    search_volume: 72000,
    difficulty: 62.0,
    relevance_score: 89.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 14,
    brand: false,
    chance: 0.55,
    kei: 1161.0,
    results: 6800,
    maximum_reach: 72000,
    conversion_rate: 0.09,
  },
  {
    keyword: "cleopatra",
    search_volume: 68000,
    difficulty: 60.0,
    relevance_score: 87.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 15,
    brand: false,
    chance: 0.58,
    kei: 1133.0,
    results: 6200,
    maximum_reach: 68000,
    conversion_rate: 0.08,
  },

  // Medium Volume Generic Keywords
  {
    keyword: "slot games",
    search_volume: 125000,
    difficulty: 65.0,
    relevance_score: 96.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 16,
    brand: false,
    chance: 0.52,
    kei: 1923.0,
    results: 18000,
    maximum_reach: 125000,
    conversion_rate: 0.09,
  },
  {
    keyword: "free casino slots",
    search_volume: 95000,
    difficulty: 58.0,
    relevance_score: 95.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "subtitle",
    sort_order: 17,
    brand: false,
    chance: 0.60,
    kei: 1638.0,
    results: 12000,
    maximum_reach: 95000,
    conversion_rate: 0.10,
  },
  {
    keyword: "jackpot",
    search_volume: 185000,
    difficulty: 72.0,
    relevance_score: 90.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 18,
    brand: false,
    chance: 0.48,
    kei: 2570.0,
    results: 24000,
    maximum_reach: 185000,
    conversion_rate: 0.08,
  },
  {
    keyword: "daily rewards",
    search_volume: 42000,
    difficulty: 45.0,
    relevance_score: 88.0,
    category: "generic",
    priority: "medium",
    platform: "both",
    recommended_field: "description",
    sort_order: 19,
    brand: false,
    chance: 0.65,
    kei: 933.0,
    results: 3800,
    maximum_reach: 42000,
    conversion_rate: 0.09,
  },

  // Competitor Keywords (Defensive)
  {
    keyword: "slotomania",
    search_volume: 150000,
    difficulty: 90.0,
    relevance_score: 35.0,
    category: "competitor",
    priority: "low",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 20,
    brand: false,
    chance: 0.15,
    kei: 166.7,
    results: 85000,
    maximum_reach: 150000,
    conversion_rate: 0.03,
  },
  {
    keyword: "huuuge casino",
    search_volume: 98000,
    difficulty: 85.0,
    relevance_score: 32.0,
    category: "competitor",
    priority: "low",
    platform: "both",
    recommended_field: "keywords",
    sort_order: 21,
    brand: false,
    chance: 0.18,
    kei: 115.3,
    results: 52000,
    maximum_reach: 98000,
    conversion_rate: 0.04,
  },
  {
    keyword: "doubleu casino",
    search_volume: 125000,
    difficulty: 88.0,
    relevance_score: 30.0,
    category: "competitor",
    priority: "low",
    platform: "both",
    recommended_field: "description",
    sort_order: 22,
    brand: false,
    chance: 0.12,
    kei: 142.0,
    results: 78000,
    maximum_reach: 125000,
    conversion_rate: 0.02,
  },
  {
    keyword: "big fish casino",
    search_volume: 85000,
    difficulty: 82.0,
    relevance_score: 28.0,
    category: "competitor",
    priority: "low",
    platform: "both",
    recommended_field: "description",
    sort_order: 23,
    brand: false,
    chance: 0.16,
    kei: 103.7,
    results: 48000,
    maximum_reach: 85000,
    conversion_rate: 0.03,
  },

  // iOS Specific
  {
    keyword: "app store slots",
    search_volume: 38000,
    difficulty: 42.0,
    relevance_score: 82.0,
    category: "generic",
    priority: "medium",
    platform: "ios",
    recommended_field: "description",
    sort_order: 24,
    brand: false,
    chance: 0.58,
    kei: 905.0,
    results: 4200,
    maximum_reach: 38000,
    conversion_rate: 0.07,
  },

  // Android Specific
  {
    keyword: "google play slots",
    search_volume: 45000,
    difficulty: 48.0,
    relevance_score: 80.0,
    category: "generic",
    priority: "medium",
    platform: "android",
    recommended_field: "description",
    sort_order: 25,
    brand: false,
    chance: 0.55,
    kei: 937.5,
    results: 4800,
    maximum_reach: 45000,
    conversion_rate: 0.08,
  },
]
